### ISSUE TITLE
As a HDP admin, I want to use a configured HDP user to create folders on HDFS

### ISSUE THREAD

**Issue by Nyna71** [jpoullet2000/det#4]
When using POST /entity/hdfs_path, it seems that the user used to create the folder on HDFS is the one that launched the DET API. The user should be configurable, and actually it seems there exist a parameter for it in settings.py

`HDFS_USER = 'hdfs'`

`dfs.util.HdfsError: Permission denied: user=Jonathan, access=WRITE, inode="/data/d0/raw/RAW/OCS":hdfs:hdfs:drwxr-xr-x`

**Comment by jpoullet2000** [comment]
Done in f51efff801ff7b67eae4816d4672b01e3aa66a31
